### set a name for the request to be used for the token
# @name login_user_request
POST https://tripapi.cphbusinessapps.dk/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "password": "user123"
} 

@user_token = {{ login_user_request.response.body.token }}

###
# @name login_admin_request
POST https://tripapi.cphbusinessapps.dk/api/auth/login HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin123"
} 

@admin_token = {{ login_admin_request.response.body.token }}

### open endpoint
GET https://tripapi.cphbusinessapps.dk/api/trips

### needs user
GET https://tripapi.cphbusinessapps.dk/api/trips/1
Authorization: Bearer {{user_token}}

### needs admin
GET https://tripapi.cphbusinessapps.dk/api/guides
Authorization: Bearer {{admin_token}}
